### ISSUE TITLE
보안 이슈 제보

### ISSUE THREAD

**Issue by dittos** [ridi/pay-backend#4]
안녕하세요.
코드를 구경하다가 보안 취약점을 발견한 것 같습니다.
공개된 이슈로 올리면 안될텐데, 어디를 통해 알려드리면 될까요?

**Comment by limeburst** [comment]
@dittos 태호님, 안녕하세요.

리디페이에 대한 보안 취약점은 security@ridi.com 을 통해 제보받고 있습니다!
